import { copyFile, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const generated = join(here, ".tailwind.generated.css");
const output = join(root, "dashboard/static/css/main.css");

const command = join(here, "node_modules/.bin/tailwindcss");
const result = spawnSync(command, ["-i", join(here, "src/theme.css"), "-o", generated, "--minify"], {
  cwd: here,
  encoding: "utf8",
});
if (result.status !== 0) {
  process.stderr.write(result.stdout || "");
  process.stderr.write(result.stderr || "");
  process.exit(result.status || 1);
}

const [tailwind, tokens, components, v3, themes] = await Promise.all([
  readFile(generated, "utf8"),
  readFile(join(here, "src/tokens.css"), "utf8"),
  readFile(join(here, "src/components.css"), "utf8"),
  readFile(join(here, "src/v3.css"), "utf8"),
  readFile(join(here, "src/themes.css"), "utf8"),
]);
const banner = "/* GENERATED by frontend/build.mjs — do not edit dashboard/static/css/main.css directly. */\n";
await writeFile(output, `${banner}${tailwind}\n${tokens}\n${components}\n${v3}\n${themes}\n`);
await rm(generated, { force: true });

const fontDir = join(root, "dashboard/static/fonts");
await mkdir(fontDir, { recursive: true });
await copyFile(
  join(here, "node_modules/@fontsource/inter/files/inter-latin-400-normal.woff2"),
  join(fontDir, "inter-latin.woff2"),
);
await copyFile(
  join(here, "node_modules/@fontsource/inter/files/inter-latin-600-normal.woff2"),
  join(fontDir, "inter-latin-600.woff2"),
);
await copyFile(
  join(here, "node_modules/@fontsource/inter/files/inter-latin-700-normal.woff2"),
  join(fontDir, "inter-latin-700.woff2"),
);
await copyFile(
  join(here, "node_modules/@fontsource/jetbrains-mono/files/jetbrains-mono-latin-400-normal.woff2"),
  join(fontDir, "jetbrains-mono-latin.woff2"),
);
await copyFile(
  join(here, "node_modules/lucide/dist/umd/lucide.min.js"),
  join(root, "dashboard/static/js/lucide.min.js"),
);

process.stdout.write(`Built ${output} with pinned Tailwind/shadcn tokens and local assets.\n`);
